# Generated by Django 4.2 on 2025-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('v1', models.CharField(max_length=500)),
                ('v2', models.CharField(max_length=500)),
                ('v3', models.CharField(max_length=500)),
                ('v4', models.CharField(max_length=500)),
                ('correct', models.CharField(choices=[('1', models.CharField(max_length=500)), ('2', models.CharField(max_length=500)), ('3', models.CharField(max_length=500)), ('4', models.CharField(max_length=500))], max_length=1)),
            ],
        ),
    ]
